sudo: required
language: node_js
node_js: 10.15.3
yarn: 1.15.2
cache: yarn

before_install:
    - npm config set registry=http://registry.npm.taobao.org

install: yarn

branches:
    only:
        - master
        - test

script: ./bin/build.sh
