sudo: true
language: node_js
node_js: 10.15.3

cache:
    directories:
        - node_modules

before_install:
    - npm config set registry=http://registry.npm.taobao.org
    - npm install -g yarn@1.15.2
    - yarn install

branches:
    only:
        - master
        - test
script:
    - yarn build
    - yarn build:test
